"""Export scan results as HTML or Markdown."""
from __future__ import annotations

import html
from typing import Any

from .scanner import load_artifact


def export_markdown(scan_id: str) -> str:
    status = load_artifact(scan_id, "status.json") or {}
    tree = load_artifact(scan_id, "tree.json")
    risks = load_artifact(scan_id, "risks.json")
    vulns = load_artifact(scan_id, "vulns.json")
    hotspots = load_artifact(scan_id, "hotspots.json")
    brief = load_artifact(scan_id, "brief.json")

    root = status.get("root_path", scan_id)
    totals = status.get("totals") or {}
    lines = [
        "# AICodeCartographer Report",
        "",
        f"- **Repository:** `{root}`",
        f"- **Scan ID:** `{scan_id}`",
        f"- **Files:** {totals.get('files', 0)} · **Lines:** {totals.get('lines', 0)}",
        "",
    ]

    if brief:
        lines.extend(
            [
                "## Architecture brief",
                "",
                brief.get("purpose", ""),
                "",
                f"- **Modules:** {brief.get('modules', '')}",
                f"- **Tech:** {brief.get('tech_stack', '')}",
                f"- **Hubs:** {brief.get('dependency_hubs', '')}",
                "",
            ]
        )
        if brief.get("top_risks"):
            lines.append("### Top risks")
            for r in brief["top_risks"]:
                lines.append(f"- {r}")
            lines.append("")
        if brief.get("top_vulns"):
            lines.append("### Top vulnerabilities")
            for v in brief["top_vulns"]:
                lines.append(f"- {v}")
            lines.append("")

    if hotspots:
        lines.append("## Hotspots (largest files)")
        for e in (hotspots.get("largest") or [])[:10]:
            lines.append(f"- `{e.get('path')}` — {e.get('lines', 0)} lines")
        lines.append("")

    if risks:
        lines.append("## Heuristic risks")
        for f in (risks.get("findings") or [])[:30]:
            loc = f.get("path") or ""
            if f.get("line"):
                loc += f":{f['line']}"
            lines.append(f"- **[{f.get('severity')}]** {f.get('title')} (`{loc}`)")
            if f.get("remediation"):
                lines.append(f"  - Fix: {f['remediation']}")
        lines.append("")

    if vulns:
        lines.append("## Dependency vulnerabilities (OSV)")
        for pkg in vulns.get("packages") or []:
            for v in pkg.get("vulnerabilities") or []:
                lines.append(
                    f"- **{pkg.get('name')}@{pkg.get('version')}** — {v.get('vuln_id')} "
                    f"({v.get('severity', 'unknown')})"
                )
                if v.get("summary"):
                    lines.append(f"  - {v['summary']}")
        lines.append("")

    if tree:
        lines.append("## File tree (sample)")
        paths = _paths_from_tree(tree)
        for p in paths[:40]:
            lines.append(f"- `{p}`")
        if len(paths) > 40:
            lines.append(f"- … and {len(paths) - 40} more")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by AICodeCartographer*")
    return "\n".join(lines)


def export_html(scan_id: str) -> str:
    md = export_markdown(scan_id)
    body = "".join(
        f"<p>{html.escape(line)}</p>" if line and not line.startswith("#") and not line.startswith("-")
        else f"<h2>{html.escape(line[3:])}</h2>" if line.startswith("## ")
        else f"<h1>{html.escape(line[2:])}</h1>" if line.startswith("# ")
        else f"<li>{html.escape(line[2:])}</li>" if line.startswith("- ")
        else "<br/>"
        for line in md.splitlines()
    )
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/>
<title>Report {html.escape(scan_id)}</title>
<style>
body{{font-family:system-ui,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;
background:#0f1419;color:#e2e8f0;line-height:1.5}}
h1,h2{{color:#f1f5f9}} li{{margin:.25rem 0}}
code{{background:#1e293b;padding:.1em .35em;border-radius:4px}}
</style></head><body>{body}</body></html>"""


def _paths_from_tree(tree: dict[str, Any]) -> list[str]:
    out: list[str] = []

    def walk(node: dict[str, Any]) -> None:
        if not node.get("is_dir"):
            out.append(str(node.get("path", "")))
        for c in node.get("children") or []:
            if isinstance(c, dict):
                walk(c)

    root = tree.get("root")
    if isinstance(root, dict):
        walk(root)
    return sorted(p for p in out if p)
